name: Docker Image CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout repository

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Tag Docker image
      run: |
        IMAGE_TAG="my-image-name:latest"
        docker tag my-image-name:$(date +%s) $IMAGE_TAG

    - name: Push Docker image to Docker Hub
      run: |
        docker push my-image-name:$(date +%s)
        docker push my-image-name:latest
